import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/shared/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie Haat Action",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Header></Header>
        {children}
        </body>
    </html>
  );
}
